export { default as dashboard } from './dashboard.vue'
export { default as userManage } from './userManage.vue'
export { default as productManage } from './productManage.vue'
export { default as categoryManage } from './categoryManage.vue'
export { default as orderManage } from './orderManage.vue'
export { default as reportManage } from './reportManage.vue'
